### PR TITLE
add support for manifest lists and fix double deletions

### PR DESCRIPTION
**Pull request by joniw**
Hello,

i added support for manifest lists (https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list) to allow cleanup of repositories containing them.

I also lowered the number delete requests.

With regards

Joniw

### CODE REVIEW

**Comment by mortensteenrasmussen** [comment]
Hi, 

Thanks for your contribution. Can I ask what changed? Also, did you test it (also that it still works with non-manifest images?

Regards,
Morten

**Comment by joniw** [comment]
Hello,

i only changed the source branch from master to manifestlist. I made no changes in the code itself.

I tested the code against my private repository but not every possible image. In the repository i use architecture namespaces like "amd64" "arm32v6" and "arm64v8". These are normal images. After an image is created a manifest list is created under the namespace "library". I used the script multiple times against this repository and i am still able to pull images from the library namespace and the architecture namespaces.

If you have some special cases i would like to test them against my private repository.

With regards,

Joniw

**Comment by mortensteenrasmussen** [comment]
I'd just like to make sure that it still works against the normal (non-manifest) use-case - e.g. someone overwriting a `latest` tag with a nightly build or something like that. I don't have any testing infrastructure up at the moment, so if you could test that, I can merge it right away :)

It'd just be building a regular image and then changing some of the source and rebuilding with the same tag, and then check if the script actually removes the old blobs/layers.

**Comment by joniw** [comment]
Hello,

i found some time to test the "not manifest list" case. I just built and tagged the image for the cleanup and pushed it to an empty registry. Then i added a line into the dockerfile which created a file and tagged and uploaded again. No manifest lists were used. Then i ran the cleanup and as expected the manifest was cleaned:

```
/ # ./docker-registry-cleanup.sh
Found 1 manifests. Starting to clean up
## Doing 1 / 1
Job done, Cleaned 1 of 1 manifests.
```

A subsequent pull was also successful.

```
docker pull localhost:5000/test/test
Using default tag: latest
latest: Pulling from test/test
d6a5679aa3cf: Already exists
ad0eac849f8f: Already exists
2261ba058a15: Already exists
f296fda86f10: Already exists
bcd4a541795b: Already exists
6b5265f48cd5: Already exists
0324ca172242: Pull complete
5e0d9561fd38: Pull complete
Digest: sha256:4c33bd8b778f18465d1269527b575fb6a5b33fbf2f557abb0a93cd9a732fda5f
Status: Downloaded newer image for localhost:5000/test/test:latest
```

**Comment by mortensteenrasmussen** [comment]
Thanks a bunch!

**Pull request merged**
